# Board: Seeed XIAO ESP32S3 (Seeed Studio)
# Definition: definitions/boards/seeed-xiao-esp32s3/manifest.yaml
# | ePaper Pin   | NameSPI FunctionRecommended XIAO ESP32-S3 Pin
# |--------------|----------------------------|--------------------
# | VCC Power    | (3.3V)                     | 3V3
# | GND          | Ground                     | GND
# | SDA          | MOSI (Master Out Slave In) | D10 (GPIO9 / Hardware MOSI)
# | SCL          | SCLK (Clock)               | D8 (GPIO7 / Hardware SCK)
# | CS           | Chip Select                | D7 (GPIO44) or any free GPIO
# | D/C (or DC)  | Data / Command Control     | D4 (GPIO5) or any free GPIO
# | RES (or RST) | Reset                      | D2 (GPIO3) or any free GPIO
# | BUSY         | Busy Status Output         | D1 (GPIO2) or any free GPIO
esphome:
  name: epaper1
  friendly_name: epaper1
  on_boot:
    priority: -100
    then:
      - delay: 1s
      - component.update: disp

esp32:
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: components

logger:

api:
  encryption:
    key: "lfqgHwibX9saQIM3+2f4I2R7jIwEFZVdiDlBr0iON2k="

ota:
  - platform: esphome
    encryption:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: epaper1 Fallback Hotspot
    password: "g1Ge1C00WIDc"

captive_portal:

display:
  - platform: weact_epaper
    id: disp
    clk_pin: GPIO7
    mosi_pin: GPIO9
    cs_pin: GPIO44
    dc_pin: GPIO5
    reset_pin: GPIO3
    busy_pin: GPIO2
    auto_clear_enabled: true
    update_interval: 1min
    lambda: |-
      it.print(208, 4, id(title_font), TextAlign::TOP_CENTER, "Fizzy Keg Status");

      if (id(keg_smoothed).has_state()) {
        it.printf(208, 37, id(value_font), TextAlign::TOP_CENTER, "%.1f%%", id(keg_smoothed).state);
      } else {
        it.print(208, 37, id(value_font), TextAlign::TOP_CENTER, "--.-%");
      }

      it.graph(10, 72, id(keg_graph));
      it.print(10, 220, id(label_font), TextAlign::TOP_LEFT, "3 days ago");
      it.print(406, 220, id(label_font), TextAlign::TOP_RIGHT, "Now");

sensor:
  - platform: homeassistant
    id: keg_smoothed
    entity_id: sensor.living_room_kegerator_keg_smoothed
    internal: true
    on_value:
      then:
        - if:
            condition:
              lambda: return !id(keg_value_received);
            then:
              - lambda: id(keg_value_received) = true;
              - component.update: disp

graph:
  - id: keg_graph
    sensor: keg_smoothed
    duration: 3d
    width: 396
    height: 142
    x_grid: 1d
    y_grid: 10
    min_value: 0
    max_value: 100
    border: true

globals:
  - id: keg_value_received
    type: bool
    initial_value: "false"

font:
  - file: "gfonts://Roboto"
    id: title_font
    size: 28
  - file: "gfonts://Roboto"
    id: value_font
    size: 24
  - file: "gfonts://Roboto"
    id: label_font
    size: 12