# Board: Seeed XIAO ESP32S3 (Seeed Studio)
# Definition: definitions/boards/seeed-xiao-esp32s3/manifest.yaml
# | ePaper Pin   | NameSPI FunctionRecommended XIAO ESP32-S3 Pin
# |--------------|----------------------------|--------------------
# | VCC Power    | (3.3V)                     | 3V3
# | GND          | Ground                     | GND
# | SDA          | MOSI (Master Out Slave In) | D10 (GPIO9 / Hardware MOSI)
# | SCL          | SCLK (Clock)               | D8 (GPIO7 / Hardware SCK)
# | CS           | Chip Select                | D7 (GPIO44) or any free GPIO
# | D/C (or DC)  | Data / Command Control     | D4 (GPIO5) or any free GPIO
# | RES (or RST) | Reset                      | D2 (GPIO3) or any free GPIO
# | BUSY         | Busy Status Output         | D1 (GPIO2) or any free GPIO
esphome:
  name: epaper1
  friendly_name: epaper1
  on_boot:
    priority: -100
    then:
      - delay: 1s
      - component.update: disp

esp32:
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: components

logger:

api:
  encryption:
    key: "lfqgHwibX9saQIM3+2f4I2R7jIwEFZVdiDlBr0iON2k="

ota:
  - platform: esphome
    encryption:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: epaper1 Fallback Hotspot
    password: "g1Ge1C00WIDc"

captive_portal:

display:
  - platform: weact_epaper
    id: disp
    clk_pin: GPIO7
    mosi_pin: GPIO9
    cs_pin: GPIO44
    dc_pin: GPIO5
    reset_pin: GPIO3
    busy_pin: GPIO2
    auto_clear_enabled: true
    update_interval: never
    lambda: |-
      it.print(40, 80, id(my_font), "TEST");

font:
  - file: "gfonts://Roboto"
    id: my_font
    size: 32